"""empty message

Revision ID: be114fa808a9
Revises: 
Create Date: 2022-01-06 16:45:52.686443

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'be114fa808a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_table',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('database', sa.String(length=50), nullable=True),
                    sa.Column('schema', sa.String(length=50), nullable=True),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('description', sa.String(length=100), nullable=True),
                    sa.Column('owner', sa.String(length=50), nullable=True),
                    sa.Column('update_frequency', sa.String(length=1), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_meta_table', 'meta_table', ['database', 'schema', 'name'], unique=True)
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=50), nullable=False),
                    sa.Column('first_name', sa.String(length=20), nullable=True),
                    sa.Column('last_name', sa.String(length=20), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('meta_column',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('table_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('data_type', sa.String(length=20), nullable=True),
                    sa.Column('description', sa.String(length=100), nullable=True),
                    sa.Column('is_pk', sa.Boolean(), nullable=False),
                    sa.Column('nullable', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['table_id'], ['meta_table.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_meta_column', 'meta_column', ['table_id', 'name'], unique=True)
    op.create_table('meta_code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('column_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('description', sa.String(length=100), nullable=True),
                    sa.ForeignKeyConstraint(['column_id'], ['meta_column.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_code')
    op.drop_index('idx_meta_column', table_name='meta_column')
    op.drop_table('meta_column')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('idx_meta_table', table_name='meta_table')
    op.drop_table('meta_table')
    # ### end Alembic commands ###
